### ISSUE TITLE
HA - Vista 20P zones cycling from open to close and back again

### ISSUE THREAD

**Issue by jl-678** [Cinntax/pyenvisalink#28] opened 2022-10-03 13:30 UTC
Many of us using HA are seeing the above behavior with our 20P.  The behavior appears to happen when we have more than 4 or 5 sensors open.  Below that number, everything behaves as expected; and once exceeded, the log shows these sensors gyrating between open and closed incessantly even when the related item is not changing.

I am not sure why this is and if it is even an issue with pyenvisalink.  It is worth noting that the Envisalink web GUI does not show this behavior and so it feels like this is something specific to pyenvisalink/HA.  

Any help anyone can provide would be appreciated.

I am currently running with HA 2022.9.1, but I have seen this with previous releases as well.

**Comment by ufodone** [comment] 2023-01-03 00:59
Hi @jl-678, apologies for the very slow response - I never got a notification when the issue was opened and just noticed it now.

If this is still an issue for you, I can try to help.  I don't have a Honeywell system myself but if you could provide debug info I may be able to help track down the issue.

**Comment by jl-678** [comment] 2023-01-03 17:47
Yes, it is definitely still an issue. It is not front and center for me as it is winter time so few zones are open.  However, once Spring returns and we open doors and windows, this problem will return.

The description above is consistent.  I think that the best place to get more information is to look at the thread linked below where Scott and I discuss the issue.  We also tried some troubleshooting related to zonedump Interval and that did not seem to help.

https://community.home-assistant.io/t/envisalink-evl-4-zones-randomly-opening-and-closing/336978/14?u=jl_678

**Comment by ufodone** [comment] 2023-01-04 23:24
If you're able to provide debug logging of the issue occurring then I can have a look at what's going on.  I'd need the pyenvisalink debug logging and not just the HA envisalink integration logging.  But keep in mind that the password and alarm code might be present so best to scrub them before uploading any logs (or use temporary values). 

It would be best if you could attach the log file rather than cut-and-pasting it.  Thanks!

**Comment by jl-678** [comment] 2023-01-05 00:46
Thanks. I want to be sure that I get the right log for you.  On [this page,](https://www.home-assistant.io/integrations/logger/) it suggests this setting:

```
logger:
  logs:
    homeassistant.components.envisalink: debug
```
Is that right? And if so, is that sufficient?  If not, where do I find the pyenvisalink logs? Maybe in the CLI somewhere? Before you ask, I am knowledgeable in Linux, Python and HA.

**Comment by ufodone** [comment] 2023-01-05 01:21
You'll also need to add `pyenvisalink` to your logging config:

```
logger:
  logs:
    homeassistant.components.envisalink: debug
    pyenvisalink: debug
```

The `pyenvisalink` logs will be included with the rest of the HA logging (in home-assistant.log).

**Comment by jl-678** [comment] 2023-01-05 23:58
Thank you! I will work to get you some logs this weekend and have asked others to do the same.

**Comment by ufodone** [comment] 2023-01-13 04:19
While I was working on the [envisalink_new](https://github.com/ufodone/envisalink_new) refactor I had a look at the zone timer dump code as it seems to be a point of issue for many people and is likely related to your issue here.

I found a bug in it but there are also some comments in the code from the original author about how the EVL seems to report the data inaccurately.  However, my own EVL works as documented which has be wondering whether the bug I found was original cause or perhaps an older version of the EVL firmware had a problem that has subsequently been fixed.

Would you be able to send me some debug logs with the zone dump timer enabled so I can verify the behaviour on a Honeywell system?  I don't need you to reproduce the case when there are several zones open.  I just need to see what happens when a single zone opens and then closes.

A simple test as follows would be great:
1. Set your zone dump timer interval to 5 seconds.
2. Turn on pyenvislink debug logging as described above.
3. Start up HA.
4. Once things are started up, open a zone (e.g. open a door) and leave it open for 10 or 15 seconds and then close it and leave it closed for 10-15 seconds.
5. Grab the logs.

If your system behaves like mine is, there might be a really simple fix for this.  🤞

**Comment by sheyman1** [comment] 2023-01-25 00:43
I'm happy to test right now, I've already added the logging text to my config.yaml.  Silly question, can someone please tell me which logs to grab and how to pull and send them?
Thank you
Scott

**Comment by ufodone** [comment] 2023-01-25 01:16
Once you have the logging enabled, it will be the main home-assistant.log file that I'd like to have a look at.  Probably the easiest way to get the file is to go into Settings->Logs and then at the bottom of the page there should be a "Download Full Log" button.  That will download and save the log file to your computer.  From there you should be able to just drag-and-drop it into a comment box on this page.

Thanks!

**Comment by ufodone** [comment] 2023-01-25 01:24
Please also confirm which version of the Envisalink you have (3 or 4).  Thanks!

**Comment by sheyman1** [comment] 2023-01-25 01:49
EVL-4 with firmware version  01.04.182A
Honeywell Vista 20p

**Comment by sheyman1** [comment] 2023-01-25 03:00
[home-assistant_2023-01-25T02-17-21.711Z.zip](https://github.com/ufodone/pyenvisalink/files/10495759/home-assistant_2023-01-25T02-17-21.711Z.zip)

**Comment by sheyman1** [comment] 2023-01-25 03:01
Hope this helps.  Thanks for all your help on this!!!

**Comment by ufodone** [comment] 2023-01-25 03:36
I see why your log file was filling up so fast now.  It looks like debug was on for all of Home Assistant.  But for future maybe setting the default to info would be good:

```
logger:
  default: info
  logs:
    homeassistant.components.envisalink: debug
    pyenvisalink: debug
```

Just to confirm: are these logs reproducing the flapping issue that was initially reported or was it meant to be a test about the zone timer dumps?  If the latter, it looks like you didn't set the `zonedump_interval` to 5 in the configuration.  The high frequency here (vs the 30 second default) is needed so I can see how they are functioning in the envisalink itself.

If the repro was showing the flapping from the initial issue, I'll dig into the logs to see what I can find.

**Comment by sheyman1** [comment] 2023-01-25 06:39
Weird, that is exactly how I set my config, here is a direct copy from my
config.yaml (I had to rem it out with the # on each line to stop it from
filling the drive but what I sent before was obviously without the #)  When
I remove those #'s my log fills about 20mb per minute, not sure why???

#logger:
#  logs:
#    homeassistant.components.envisalink: debug
#    pyenvisalink: debug

And yes, to confirm, the log I uploaded was showing the flapping in full
swing.  I am more than happy / willing to test in any way that can help you
to fix this issue, just let me know what it is I can do or provide to help.

**Comment by ufodone** [comment] 2023-01-25 16:02
I cut-and-pasted the log config from above and realized I didn't add the extra "default: info" line and then went back and edited it so you maybe didn't see that addition.

I had a look at the logs and confirmed my suspicions as to what's going on.  Would be able to run the other test I posted above of setting the zonedump_interval to 5?  That would help determine how I could approach fixing the issue.

**Comment by sheyman1** [comment] 2023-01-25 18:33
OK, I changed my config to add "default: info" and also changed zonedump_interval to 5.  I then restarted HA and opened 4 windows and 1 door.  I let that run for several minutes and should show the flapping of the windows and doors.  The motion entries are probably me walking around initially opening the above but after the motion stops you should see the flapping.  I let it run for a few minutes then saved the first log.  After that I manually closed the door and windows then saved the log again in case you wanted to see it including me actually closing the door and windows.  
Thanks again for all your help with this.
Scott
[home-assistant_2023-01-25T18-20-20.1
[home-assistant_2023-01-25T18-22-42.361Z.log](https://github.com/ufodone/pyenvisalink/files/10502424/home-assistant_2023-01-25T18-22-42.361Z.log)
28Z.log](https://github.com/ufodone/pyenvisalink/files/10502422/home-assistant_2023-01-25T18-20-20.128Z.log)

**Comment by ufodone** [comment] 2023-01-26 02:20
Thanks for the additional logs.  That gives me enough to go on.

I'll see what I can put together for a fix.  I'll likely put and changes into the [new](https://github.com/ufodone/envisalink_new) version I'm working on first as it's faster to iterate on changes there.  I'll update here once I think I've got something worth testing.

**Comment by sheyman1** [comment] 2023-01-26 07:00
Thank you!!!  If you need anything additional at all from me please let me know. Am happy to helpSent from my iPhoneOn Jan 25, 2023, at 6:20 PM, ufodone ***@***.***> wrote:﻿
Thanks for the additional logs.  That gives me enough to go on.
I'll see what I can put together for a fix.  I'll likely put and changes into the new version I'm working on first as it's faster to iterate on changes there.  I'll update here once I think I've got something worth testing.

**Comment by sheyman1** [comment] 2023-01-30 21:44
Envisalink_new seems to be working ok for me except that the open zone flapping is still happening just as before.  My config shows the following for logging to try to help you.  Attached is the log, I restarted then opened around 5 doors / windows.  Let me know what else I can do to help with this...
Thank you

logger:
  default: info
  logs:
    homeassistant.components.envisalink: debug
    pyenvisalink: debug
[home-assistant_2023-01-30T21-40-10.693Z.log](https://github.com/ufodone/pyenvisalink/files/10540222/home-assistant_2023-01-30T21-40-10.693Z.log)

**Comment by ufodone** [comment] 2023-01-30 22:14
Hey @sheyman1 Let's take the conversation over [here](https://github.com/ufodone/envisalink_new/issues/9) since this isn't the HA core version.  Thanks!

**Comment by sheyman1** [comment] 2023-01-30 22:50
Sorry, my bad, missed the log change.  I will run the test again now with
the _new logging info corrected and post the log to the link above.

Thanks

**Comment by ufodone** [comment] 2023-05-08 03:57
Closing this issue as I believe this issue is fixed in [envisalink_new](https://github.com/ufodone/envisalink_new).

**Closed as completed by ufodone** 2023-05-08 03:57 UTC

**Comment by AntoineDeveloper** [comment] 2024-07-11 21:21
What was the fix... I do not want to change my 32 zones from the old plugin to the new one, I have so many automations on them all... is there another way @ufodone

**Comment by ufodone** [comment] 2024-07-13 01:16
@AntoineDeveloper The algorithm used to track zone state changes was replaced with one that used a different set of updates from the EVL devices.  I have no plans to move these changes back into the old integration so currently the only option is to switch to `envisalink_new`.  

FYI, `envisalink_new` can import all your config from the stock integration which will preserve the entity names and so I suspect that most of your automations wouldn't need updating.  Only places where the integration name is used should be affected.  E.g. service calls to `Alarm Keypress` and `Invoke Custom Function`.
